### ISSUE TITLE
Angular: Could not find a declaration file for module 'name-spell-checker'

### ISSUE THREAD

**Issue by PHuhn** [zjffun/name-spell-checker#1]
I am working with Angular 12.  I added the package as folows:

`npm --save-dev install name-spell-checker nspell`

I added a class as follows:

`ng g class katas/wonderland-doublets/Doublets`

I changed the class as follows:

```
import { NameSpellChecker } from 'name-spell-checker';
//
export class Doublets {
    spellChecker = new NameSpellChecker( );
}
```

Error message with 'name-spell-checker' highlighed in the import statement:
```
Could not find a declaration file for module 'name-spell-checker'. 'c:/Dat/Nsg/L/Web/Ng/katas/node_modules/name-spell-checker/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/name-spell-checker` if it exists or add a new declaration (.d.ts) file containing `declare module 'name-spell-checker';`ts(7016)
```

I tried the suggestion in the message but no change.

**Comment by zjffun** [comment]
Thank you. I fix this in v0.0.3. 4638592cfc073b5f958819abe4439239326d529c
